### ISSUE TITLE
Fantom Interpreter Library for SkySpark 3.0 no longer works with F4's code completion

### ISSUE THREAD

**Issue by buddyp450** [xored/f4#101]
https://skyfoundry.com/forum/topic/2525#c1

I don't know enough about Eclipse plugins to effectively debug why this is but I thought it was worth noting for anyone thinking about using F4 as their IDE of choice when moving from the 1.0.67.15 fantom interpreter library in SkySpark 2.x to 3.0's 1.0.68 interpreter would benefit knowing this advertised feature of the F4 IDE does not work in 3.0.

Error is: "Computation of proposals takes too long. Please try again"

If anyone knows of the specific eclipse arg to increase the timeout for proposal generation, please let me know. I've already increased the heap size for eclipse in the hopes that it would help to no avail.

Workaround: I created a subset of pods that I'm actually using by removing many of the pods that came with the interpreter and it seems to be working now. I don't know where or how the limit is being set.

**Comment by SlimerDude** [comment]
I suspect this is now okay in F4 1.1.4 (lots of speed enhancement have been made to various areas) - but if not, the work around is to use the F4-FPM plugin ( https://github.com/Fantom-Factory/afF4Fpm ) as that limits referenced pods to just the ones the project uses.
