### ISSUE TITLE
Treat .fwt file the same as .fan source file

### ISSUE THREAD

**Issue by hoper-a11y** [xored/f4#120]
It seemed f4 doesn't highlight and provide auto-completion for .fwt file. f4 should treat both of them the same as they are both fan source file.

**Comment by SlimerDude** [comment]
Forgive my ignorance, but what is an `.fwt` file?

Do you have a link to where it is defined?

**Comment by hoper-a11y** [comment]
They are on /fantom-1.0.74/examples/js. The code inside them looked just like normal fantom source.

**Comment by SlimerDude** [comment]
Ah - that's not a standard, it's just a _fudge_ that particular example uses to distinguish between client and server code.

Try right-clicking on the source in F4 and select `Open With -> Other -> Fantom Source Editor`.
