### ISSUE TITLE
Allow installing of f4 into existing Eclipse

### ISSUE THREAD

**Issue by hoper-a11y** [xored/f4#121]
On FreeBSD/DragonflyBSD, we have unofficial port of Eclipse. By allowing install of f4 into existing Eclipse, you also extended f4 to FreeBSD/DragonflyBSD.

**Comment by SlimerDude** [comment]
I believe it can already be done...

 1. Download `f4-1.1.4-repository.zip` from the [Releases tab](/xored/f4/releases)
 2. Bring up the Install dialogue in eclipse by clicking `Help -> Install new software...`
 3. Drop the .zip file into the `work with:` textbox at the top of the dialogue (or type in the location of the .zip file)
 4. F4 features should then become available for install.

Note it may only work on the correct install of eclipse, and you'll probably need to install [DLTK](http://download.eclipse.org/technology/dltk/updates-dev/5.10/) first too.

If you're able to install it, then I can update the readme with instructions.

**Comment by hoper-a11y** [comment]
The correct version of Eclipse is the really trouble. On FreeBSD, we have the latest Eclipse:

https://www.freshports.org/java/eclipse/

The current version of f4 is based on Eclipse 4.9, isn't it? I don't know if f4 could be installed into newer Eclipse version.
