### ISSUE TITLE
String interpolation doesn not work for depends List 

### ISSUE THREAD

**Issue by beatfreaker** [xored/f4#123]
F4 is not able to build project with below `build.fan`
@SlimerDude is there any way we can assign version dynamically ?

I want to give version from environment variables as shown in code comments
```
using build

class Build : BuildPod {
	new make() {
		podName = ""
		summary = ""
		version = Version("1.0")
		version := "3.0.24" // Env.cur.vars["version"] ?: "3.0.24"
		depends = [
			"dummy ${version}"
		]
	}
}
```

**Comment by SlimerDude** [comment]
F4 does not compile and execute the `build.fan`, instead it parses expressions out of the raw code, so no it's not possible to assign versions dynamically.

But typically, you only care about versions when releasing production code / pods - and in development you're happy to take what ever is available. In that situation, you can do something like this:

```
class Build : BuildPod {
	new make() {
		podName = "foo"
		summary = "bar"
		version = Version("1.0")
		depends = [
			"dummy 3.0.24"
		]

		fromEnv := Env.cur.vars["version"]		
		this.version = Version(fromEnv)
		this.depends.remove("dummy 3.0.24")
		this.depends.add   ("dummy ${fromEnv}")		
	}
}
```

Whereby the initial settings are used by F4, and the later augmentations when the pod is built from the cmd line for production release.

But this issue does raise the larger question of build tools for Fantom, and what you're building the the pod for.

**Comment by SlimerDude** [comment]
Given this is more of a feature request (with a workaround), I'm going to close this with the comment, "Won't fix." :)
