### ISSUE TITLE
Format source code function doesn't work

### ISSUE THREAD

**Issue by CretinHo** [xored/f4#124]
Format the source does nothing. Is it even implemented?

**Comment by SlimerDude** [comment]
I don't know where you're looking, but no, there is source code formatting in F4.

**Comment by CretinHo** [comment]
> I don't know where you're looking, but no, there is source code formatting in F4.

Yes, there is an option Format to choose from. You right click on a source file and you will see the option, but it does nothing. Are you going to implement the source code formatting function for F4? It's very useful to have it.

**Comment by SlimerDude** [comment]
Ah, I see it now, thanks!

![image](https://user-images.githubusercontent.com/3326741/117107682-e46e1600-ad79-11eb-8046-0c331293d9aa.png)

But no, I'm afraid source formatting is a huge topic and isn't even on the roadmap - that option should really be removed.

If you're just converting between C# style curly brackets and Java style, then I usually just use a regular expression search / replace; it handles the job quite nicely. (But I don't have the expression to hand...)

**Comment by CretinHo** [comment]
I have problem with indent the code, though. When I copied fragments of code online to F4, they always mis indented. Seems I have to ident them myself.
