### ISSUE TITLE
Adding "icons 1.0" as a dependency prevents compilation

### ISSUE THREAD

**Issue by SlimerDude** [xored/f4#38]
Steps to recreate:

1. Create a new Fantom project in F4 using the new project wizard.
1. Create a new class, and introduce a compilation error. Example:
    ````
    class Bro ken 
    {

    }
    ````
    Note the problem in the Problems View. 
1. Add `icons 1.0` as a dependency:

    ````
    using build
    class Build : build::BuildPod
    {
      new make()
      {
        podName = "wotever"
        summary = ""
        srcDirs = [`fan/`]
        depends = ["sys 1.0", "icons 1.0"]
      }
    }
    ````
Note that the Problems View is now empty!

**Comment by komaz** [comment]
Caused by http://fantom.org/forum/topic/2386, and because of #47 this error is not properly reported
