### ISSUE TITLE
How to integrate Fantom Runtime in Maven build?

### ISSUE THREAD

**Issue by SlimerDude** [xored/f4#61]
This is question, rather than an issue - but I'm not sure where else to ask it.

I've updated the Fantom Runtime project to use [Fantom 1.0.68](https://github.com/SlimerDude/fantom-runtime/tree/feature/fantom_1.0.68) - making sure to keep the custom classloader changes. And everything seems to work fine when launched from F4.

So the question is, **How do I build F4 with `mvn package` and have it pick up my new version of Fantom Runtime?**

I've tried running `mvn install` from the Fantom Runtime project, but when I then build F4 (with all references to 1.0.63 updated to 1.0.68) I get the following error:
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: repository raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT
[ERROR]   Missing requirement: repository raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT 
          requires 'org.fantom.feature.group [1.0.68,1.0.69)' but it could not be found
```
Many thanks.

**Comment by haiodo** [comment]
Hi Steve,

This is because fantom-runtime is just with version 1.0.63, it is located here: https://github.com/xored/fantom-runtime

It is not an easy task to upgrade it to latest version.

Andrey.

**Comment by SlimerDude** [comment]
Hi Andrey - thanks for the reply.

As mentioned, I've already cloned the fantom-runtime project and (attempted) to update it to Fantom 1.0.68. See this [fantom-runtime 1.0.68 branch](https://github.com/SlimerDude/fantom-runtime/tree/feature/fantom_1.0.68).

As far as I can tell, other than updating the pods, you just need to make sure [this commit](https://github.com/xored/fantom-runtime/commit/952f8f4ea5dc591f4869c9a218e94178c0ed1b1b) is re-applied - which I did successfully. 

All seems to work happily when I launch F4 from F4. For example, I can see that Issue #49 *JS Pod Meta* has been fixed.

So, assuming my fantom-runtime is okay, how do I include it in the F4 build?

**Comment by haiodo** [comment]
During build F4 uses fantom-runtime from http://updates.xored.com/fantom-runtime/ so to test it you need to update top level pom.xml file with a proper URI, you could use file:// to point to local build URI.

**Comment by SlimerDude** [comment]
That's great. I updated F4's top level `pom.xml` to have:
```
    <repository>
      <snapshots>
        <updatePolicy>always</updatePolicy>
      </snapshots>
      <id>fantom-runtime</id>
      <layout>p2</layout>
      <url>file:///D:/Projects/fantom-runtime/org.fantom-updatesite/target/site/</url>
    </repository>
```
And the build worked perfectly - thanks for the tip!
