### ISSUE TITLE
Add support for external builder considering new launching

### ISSUE THREAD

**Issue by iinozemtsev** [xored/f4#7]
After #2 change need to add the code which will copy the compiled pod after external builder to the location where launcher expects to find it

**Comment by SlimerDude** [comment]
Err, I have no idea what this issue is all about. If no one else does either then I would vote to close it.

**Comment by SlimerDude** [comment]
I'm closing issue for the new environment features should make this a non-issue. 

If the issue still persists, please re-post with an updated description.
