### ISSUE TITLE
Autocompletion for facets suggest all classes not only facets

### ISSUE THREAD

**Issue by martianov** [xored/f4#98]
![f4-suggest-facets-bug](https://cloud.githubusercontent.com/assets/9569740/16894600/17334cc2-4b7d-11e6-8daf-6a4683f7581a.png)

**Comment by SlimerDude** [comment]
Is this an existing bug, or something that's broken in the RCPTT test?

**Comment by martianov** [comment]
RCPTT test fails on that, it's true.
I checked F4 1.0.2 and it works same way (shows not only facets):
![f4_1_0_2-suggest-facets](https://cloud.githubusercontent.com/assets/9569740/16895433/c99cfd4e-4b97-11e6-8b21-efd72d579e7f.png)
So it's not a regression bug.
But I think it may be useful improvement. So I marked this issue as 'enhancement'

**Comment by SlimerDude** [comment]
Typing `@Se + [CTRL-SPACE]` actually works as there's a `FacetCompletionProvider` in `com.xored.f4.ui.text`.

What doesn't work is the simple case of `@ + [CTRL-SPACE]` as the model parser does not recognise it as a facet type until you start typing the type name.

I may be able to fudge `FacetCompletionProvider` though...
